# Generated by Django 5.0.4 on 2024-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
