# Generated by Django 5.0.4 on 2024-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_personalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalization',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
