# Generated by Django 5.0.6 on 2024-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
