# Generated by Django 5.0.6 on 2024-05-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_personalization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalization',
            name='user',
        ),
        migrations.AddField(
            model_name='personalization',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart'),
        ),
        migrations.AddField(
            model_name='personalization',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.order_product'),
            preserve_default=False,
        ),
    ]
