# Generated by Django 5.0.6 on 2024-05-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_personalization_user_personalization_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalization',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cartitem'),
        ),
    ]
