# Generated by Django 5.0.6 on 2024-05-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_personalization_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalization',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order_product'),
        ),
    ]
