# Generated by Django 5.0.4 on 2024-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/small'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_image',
            field=models.ImageField(upload_to='products/large'),
        ),
    ]
